export default [
    {
        id: 1,
        title:"Realme narzo N55 (Prime Black, 6GB+128GB)",
        img:"https://m.media-amazon.com/images/I/81ogvU1j6qL._AC_UY218_.jpg",
        price: 9499.0,
        quantity: 1,
      },
    {
        id: 2,
        title:"TECNO POP 8 (Gravity Black,(8GB*+64GB)",
        img:"https://m.media-amazon.com/images/I/61wbxpNaD1L._AC_UY218_.jpg",
        price: 6499.0,
        quantity: 1,
      },
    {
        id: 3,
        title:"Samsung Galaxy M34 5G (Waterfall Blue,6GB,128GB)",
      img:"https://m.media-amazon.com/images/I/91L9EF-OEGL._AC_UY218_.jpg",
        price: 18499.0,
        quantity: 1,
      },
    {
        id: 4,
        title:"iQOO Z7s 5G by vivo (Pacific Night, 6GB RAM, 128GB)",
      img:"https://m.media-amazon.com/images/I/51oW-QOqhaL._AC_UY218_.jpg",
        price: 16999.0,
        quantity: 1,
      },
    {
        id: 5,
        title:"Redmi Note 13 5G (Arctic White, 6GB RAM, 128GB)",
        img:"https://m.media-amazon.com/images/I/71VW8LmqqPL._AC_UY218_.jpg",
        price: 17999.0,
        quantity: 1,
      },
    {
        id: 6,
        title:"OnePlus Nord CE 2 5G (Bahamas Blue, 8GB RAM, 128GB)",
        img:"https://m.media-amazon.com/images/I/61+Q6Rh3OQL._AC_UY218_.jpg",
        price: 19999.0,
        quantity: 1,
      },
    {
        id: 7,
        title:"Redmi Note 13 5G (Stealth Black, 6GB RAM, 128GB Storage)",
      img:"https://m.media-amazon.com/images/I/71NnrsYP63L._AC_UY218_.jpg",
        price: 17999.0,
        quantity: 1,
      },
    {
        id: 8,
        title:"iQOO Z7 Pro 5G (Blue Lagoon, 8GB RAM, 256GB Storage)",
        img:"https://m.media-amazon.com/images/I/61Id6WJDWqL._AC_UY218_.jpg",
        price: 24999.0,
        quantity: 1,
      },
    {
        id: 9,
        title: "Poco X3 Pro(Graphite Black, 6GB RAM, 128GB Storage)",
        img: "https://m.media-amazon.com/images/I/31wh13R16iL._AC_UY218_.jpg",
        price: 17479.0,
        quantity: 1,
      },
]